rem ---------------- AMBITO --------------------

DROP TABLE GCA_AMBITO CASCADE CONSTRAINTS;
CREATE TABLE GCA_AMBITO
(
  ID_AMBITO    INTEGER                          NOT NULL,
  AMBITO       VARCHAR2(512 BYTE)               NOT NULL
)
TABLESPACE TENECO_TBS;

SET DEFINE OFF;
Insert into GCA_AMBITO
   (ID_AMBITO, AMBITO)
 Values
   (1, 'RIBILITATIVO');
Insert into GCA_AMBITO
   (ID_AMBITO, AMBITO)
 Values
   (2, 'COGNITIVO');
COMMIT;

rem ---------------- GLOSSARIO --------------------

prompt Create table GCA_GLOSSARIO
DROP TABLE GCA_GLOSSARIO CASCADE CONSTRAINTS;
CREATE TABLE GCA_GLOSSARIO
(
  ID_VOCE      INTEGER        NOT NULL,
  VOCE         VARCHAR2(512)  NOT NULL,
  DEFINIZIONE  VARCHAR2(4000) 
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_GLOSSARIO
DROP SEQUENCE S_GCA_GLOSSARIO;
CREATE SEQUENCE S_GCA_GLOSSARIO START WITH 1;

create unique index  UI_GCA_GLOSSARIO  
on GCA_GLOSSARIO (VOCE)
TABLESPACE TENECO_TBS;

create unique index  UI_GCA_GLOSSARIO_ID  
on GCA_GLOSSARIO (ID_VOCE)
TABLESPACE TENECO_TBS;

rem ---------------- PATOLOGIE --------------------

-- select * from TEN_ICD9CM_DIAGNOSI 
prompt Create table GCA_PATOLOGIE
DROP TABLE GCA_PATOLOGIE CASCADE CONSTRAINTS;
CREATE TABLE GCA_PATOLOGIE
(
  ID_PATOLOGIA   INTEGER        NOT NULL,
  PATOLOGIA      VARCHAR2(255)  NOT NULL,
  COD_ICD9CMDIA  VARCHAR2(255)
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_PATOLOGIE
DROP SEQUENCE S_GCA_PATOLOGIE;
CREATE SEQUENCE S_GCA_PATOLOGIE START WITH 1;

DROP INDEX UI_GCA_PATOLOGIE_ID;
CREATE UNIQUE INDEX UI_GCA_PATOLOGIE_ID ON GCA_PATOLOGIE
(ID_PATOLOGIA)
TABLESPACE TENECO_TBS;

DROP INDEX UI_GCA_PATOLOGIE_COD;
CREATE UNIQUE INDEX UI_GCA_PATOLOGIE_COD ON GCA_PATOLOGIE
(COD_ICD9CMDIA)
TABLESPACE TENECO_TBS;

rem ---------------- PACCHETTI --------------------

prompt Create table GCA_PACCHETTI
DROP TABLE GCA_PACCHETTI CASCADE CONSTRAINTS;
/*
CREATE TABLE GCA_PACCHETTI
(
  ID_PACCHETTO       INTEGER                    NOT NULL,
  NOME_PACCHETTO     VARCHAR2(255 BYTE)         NOT NULL,
  ID_AMBITO          INTEGER,
  ID_PATOLOGIA       INTEGER,
  CONTROINDICAZIONI  VARCHAR2(4000 BYTE),
  PREREQUISITI       VARCHAR2(4000 BYTE),
  ALERT              VARCHAR2(4000 BYTE),
  DESCR_PACCHETTO    VARCHAR2(4000 BYTE)
)
TABLESPACE TENECO_TBS;
*/

CREATE TABLE GCA_PACCHETTI
(
  ID_PACCHETTO           INTEGER                NOT NULL,
  NOME_PACCHETTO         VARCHAR2(255 BYTE)     NOT NULL,
  DESCR_PACCHETTO        VARCHAR2(4000 BYTE),
  ID_AMBITO              INTEGER,
  CONTROINDICAZIONI      VARCHAR2(4000 BYTE),
  PREREQUISITI           VARCHAR2(4000 BYTE),
  ALERT                  VARCHAR2(4000 BYTE),
  ID_PATOLOGIA           INTEGER,
  ALERT_VISIBILE         VARCHAR2(4000 BYTE),
  BIBLIOGRAFIA           VARCHAR2(4000 BYTE),
  PATOLOGIE_SECONDARIE   VARCHAR2(4000 BYTE),
  VALUTAZIONE            VARCHAR2(4000 BYTE),
  NOTE                   VARCHAR2(4000 BYTE),
  CONTROINDICAZIONI_ASS  VARCHAR2(4000 BYTE),
  PREREQUISITI_COMP      VARCHAR2(4000 BYTE),
  COME_VALUTARE          VARCHAR2(4000 BYTE),
  ID_SCHEDA_VALUTAZIONE  INTEGER
)
TABLESPACE TENECO_TBS;


prompt Create sequence S_GCA_PACCHETTI_ID_PACCHETTO
DROP SEQUENCE S_GCA_PACCHETTI_ID_PACCHETTO;
CREATE SEQUENCE S_GCA_PACCHETTI_ID_PACCHETTO START WITH 1;

prompt Create unique index  UI_GCA_PACCHETTI (NOME_PACCHETTO)
create unique index  UI_GCA_PACCHETTI 
on GCA_PACCHETTI (NOME_PACCHETTO)
TABLESPACE TENECO_TBS;

create unique index  UI_GCA_PACCHETTI_ID 
on GCA_PACCHETTI (ID_PACCHETTO)
TABLESPACE TENECO_TBS;

rem -----------------------------------------------------

prompt Create table GCA_GRUPPI
DROP TABLE GCA_GRUPPI CASCADE CONSTRAINTS;

CREATE TABLE GCA_GRUPPI
(
  ID_AMBITO    INTEGER                          NOT NULL,
  ID_GRUPPO    INTEGER                          NOT NULL,
  NOME_GRUPPO  VARCHAR2(255 BYTE)               NOT NULL,
  DESC_GRUPPO  VARCHAR2(4000 BYTE)
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_GRUPPI_ID_GRUPPO
DROP SEQUENCE S_GCA_GRUPPI_ID_GRUPPO;
CREATE SEQUENCE S_GCA_GRUPPI_ID_GRUPPO START WITH 1;

prompt Create unique index  UI_GCA_GRUPPI (ID_AMBITO,NOME_GRUPPO)
create unique index  UI_GCA_GRUPPI 
on GCA_GRUPPI (ID_AMBITO, NOME_GRUPPO)
TABLESPACE TENECO_TBS;

rem -----------------------------------------------------

prompt Create table GCA_PACCHETTI_ESERCIZI
DROP TABLE GCA_PACCHETTI_ESERCIZI CASCADE CONSTRAINTS;
CREATE TABLE GCA_PACCHETTI_ESERCIZI
(
  ID_PACCHETTO   INTEGER        NOT NULL,
  ID_ESERCIZIO   INTEGER        NOT NULL,
  NOME_ESERCIZIO VARCHAR2(255)  NOT NULL,
  DESC_ESERCIZIO VARCHAR2(4000)         ,
  ID_GRUPPO      INTEGER
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_PACK_ESERC_ID_ESERCIZIO
DROP SEQUENCE S_GCA_PACK_ESERC_ID_ESERCIZIO;
CREATE SEQUENCE S_GCA_PACK_ESERC_ID_ESERCIZIO START WITH 1;

prompt Create unique index  UI_GCA_PACCHETTI_ESERCIZI (ID_PACCHETTO,NOME_ESERCIZIO)
create unique index  UI_GCA_PACCHETTI_ESERCIZI 
on GCA_PACCHETTI_ESERCIZI (ID_PACCHETTO,NOME_ESERCIZIO)
TABLESPACE TENECO_TBS;

rem -----------------------------------------------------

prompt Create table GCA_MULTIMEDIA
DROP TABLE GCA_MULTIMEDIA CASCADE CONSTRAINTS;
CREATE TABLE GCA_MULTIMEDIA
(
  ID_MEDIA      INTEGER        NOT NULL,
  URL           VARCHAR2(1024) NOT NULL,
  TIPO          VARCHAR2(100)          ,
  DESCR_MEDIA   VARCHAR2(256)  NOT NULL,
  URL_SNAPSHOT  VARCHAR2(512) ,
  URL_PARAM     VARCHAR2(512) 
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_MULTIMEDIA_ID_MEDIA
DROP SEQUENCE S_GCA_MULTIMEDIA_ID_MEDIA;
CREATE SEQUENCE S_GCA_MULTIMEDIA_ID_MEDIA START WITH 1;

prompt Create unique index UI_GCA_MULTIMEDIA (URL)
create unique index  UI_GCA_MULTIMEDIA 
on GCA_MULTIMEDIA (URL)
TABLESPACE TENECO_TBS;

rem -----------------------------------------------------

prompt Create table GCA_ESERCIZIO_MEDIA
DROP TABLE GCA_ESERCIZIO_MEDIA CASCADE CONSTRAINTS;
CREATE TABLE GCA_ESERCIZIO_MEDIA
(
  ID_PACCHETTO  INTEGER   NOT NULL,
  ID_ESERCIZIO  INTEGER   NOT NULL,
  ID_MEDIA      INTEGER   NOT NULL
)
TABLESPACE TENECO_TBS;

create unique index  UI_GCA_ESERCIZIO_MEDIA 
on GCA_ESERCIZIO_MEDIA (ID_PACCHETTO,ID_ESERCIZIO,ID_MEDIA)
TABLESPACE TENECO_TBS;


rem -----------------------------------------------------

prompt Create table GCA_TARGET_ATTIVITA

DROP TABLE GCA_TARGET_ATTIVITA CASCADE CONSTRAINTS;

CREATE TABLE GCA_TARGET_ATTIVITA
(
  ID_TARGET        INTEGER                      NOT NULL,
  URL_TARGET       VARCHAR2(1024 BYTE)          NOT NULL,
  NOME_TARGET      VARCHAR2(100 BYTE)           NOT NULL,
  LEN_NOME_TARGET  INTEGER                      NOT NULL,
  DESCR_TARGET     VARCHAR2(256 BYTE),
  ID_CAT           NUMBER
)
TABLESPACE TENECO_TBS;

prompt Create unique index UI_GCA_TARGET_ATTIVITA

CREATE UNIQUE INDEX UI_GCA_TARGET_ATTIVITA ON GCA_TARGET_ATTIVITA (URL_TARGET)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_TARGET_ATTIVITA_ID
DROP SEQUENCE S_GCA_TARGET_ATTIVITA_ID;
CREATE SEQUENCE S_GCA_TARGET_ATTIVITA_ID START WITH 1;

rem -----------------------------------------------------
DROP TABLE GCA_CATEGORIA CASCADE CONSTRAINTS;
CREATE TABLE GCA_CATEGORIA
(
  ID_CAT        INTEGER                          NOT NULL,
  CATEGORIA     VARCHAR2(512 BYTE)               NOT NULL
)
TABLESPACE TENECO_TBS;

prompt Create sequence S_GCA_CATEGORIA
DROP SEQUENCE S_GCA_CATEGORIA;
CREATE SEQUENCE S_GCA_CATEGORIA START WITH 1;

create unique index  UI_GCA_CATEGORIA  
on GCA_CATEGORIA (CATEGORIA)
TABLESPACE TENECO_TBS;

create unique index  UI_GCA_CATEGORIA_ID  
on GCA_CATEGORIA (ID_CAT)
TABLESPACE TENECO_TBS;


rem -----------------------------------------------------
DROP TABLE GCA_ANAGRAFICA_PAZIENTI CASCADE CONSTRAINTS;

CREATE TABLE GCA_ANAGRAFICA_PAZIENTI
(
  ID_PAZIENTE         NUMBER   NOT NULL,  
  CODICE_FISCALE      VARCHAR2(255 BYTE)   NOT NULL,
  COGNOME             VARCHAR2(255 BYTE)   NOT NULL,
  NOME                VARCHAR2(255 BYTE)   NOT NULL,
  SESSO               VARCHAR2(255 BYTE)   ,
  DATA_NASCITA        DATE,
  LUOGO_NASCITA       VARCHAR2(255 BYTE)   NOT NULL,
  LUOGO_RESIDENZA     VARCHAR2(255 BYTE)   NOT NULL,
  INDIRIZZO_DOMICILIO VARCHAR2(255 BYTE)  NOT NULL,
  NAZIONALITA         VARCHAR2(255 BYTE)   NOT NULL,
  EMAIL               VARCHAR2(250 BYTE),
  NOTE                VARCHAR2(1024 BYTE) 
)
TABLESPACE TENECO_TBS; 


create unique index  UI_GCA_ANAGRAFICA_PAZIENTI_ID  
on GCA_ANAGRAFICA_PAZIENTI (ID_PAZIENTE)
TABLESPACE TENECO_TBS;

create unique index  UI_GCA_ANAGRAFICA_PAZIENTI_CF  
on GCA_ANAGRAFICA_PAZIENTI (CODICE_FISCALE)
TABLESPACE TENECO_TBS;


prompt Create sequence S_GCA_ANAGRAFICA_PAZIENTI
DROP SEQUENCE S_GCA_ANAGRAFICA_PAZIENTI;
CREATE SEQUENCE S_GCA_ANAGRAFICA_PAZIENTI START WITH 1;


rem -----------------------------------------------------
DROP TABLE GCA_RESULT_APP CASCADE CONSTRAINTS;

CREATE TABLE GCA_RESULT_APP
(
  ID_USER           VARCHAR2(512 BYTE)   NOT NULL,           
  APP_NAME          VARCHAR2(512 BYTE)   NOT NULL,
  CONFIG_APP        VARCHAR2(512 BYTE)   ,
  RESULT_APP        VARCHAR2(512 BYTE)   NOT NULL,
  DATE_APP          DATE NOT NULL 
)
TABLESPACE TENECO_TBS; 


rem -----------------------------------------------------

DROP TABLE GCA_LOGIN_UTENTE CASCADE CONSTRAINTS;

CREATE TABLE GCA_LOGIN_UTENTE
(
  ID_UTENTE         NUMBER,
  PASSWD            VARCHAR2(128 BYTE),
  DATA_CREAZIONE    DATE,
  ULTIMO_ACCESSO    DATE,
  FIRST_PASSWD      VARCHAR2(128 BYTE)
)
TABLESPACE TENECO_TBS; 

create unique index  UI_GCA_LOGIN_UTENTE_ID  
on GCA_LOGIN_UTENTE (ID_UTENTE)
TABLESPACE TENECO_TBS;


DROP TABLE GCA_PAZIENTI_ESERCIZI CASCADE CONSTRAINTS;

CREATE TABLE GCA_PAZIENTI_ESERCIZI
(
  ID_PAZIENTE   INTEGER                         NOT NULL,
  ID_PACCHETTO  INTEGER                         NOT NULL,
  ID_ESERCIZIO  INTEGER                         NOT NULL
)
TABLESPACE TENECO_TBS;