SET DEFINE OFF;

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11A01H901A', 'CognomePrimo', 'Primo', 'M' ,to_date('1950-01-01','YYYY-MM-DD') , 'Roma', 'Milano', 'Via Primo 1', 'Italiana');

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11B02H901B', 'CognomeSecondo', 'Secondo','M' ,to_date('1950-01-02','YYYY-MM-DD') , 'Roma', 'Milano', 'Via Secondo 2', 'Italiana');

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11C03H901C', 'CognomeTerzo', 'Terzo','M' ,to_date('1950-01-03','YYYY-MM-DD') , 'Roma', 'Milano', 'Via Terzo 3', 'Italiana');

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11D04H901D', 'CognomeQuarta', 'Quarta','F' ,to_date('1950-01-04','YYYY-MM-DD') , 'Roma', 'Roma', 'Via Quarta 4', 'Italiana');


Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11E05H901E', 'CognomeQuinta', 'Quinta','F' ,to_date('1950-01-05','YYYY-MM-DD') , 'Firenze', 'Firenze', 'Via Quinta 5', 'Italiana');


Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11F06H901F', 'CognomeSesto', 'Sesto','M' ,to_date('1950-01-06','YYYY-MM-DD') , 'Firenze', 'Firenze', 'Via Sesto 6', 'Italiana');


Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11G07H901G', 'CognomeSettimo', 'Settimo','M' ,to_date('1950-01-07','YYYY-MM-DD') , 'Firenze', 'Firenze', 'Via Settimo 7', 'Italiana');


Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11I08H901I', 'CognomeOttavo', 'Ottavo','M' ,to_date('1950-01-08','YYYY-MM-DD') , 'Firenze', 'Firenze', 'Via Ottavo 8', 'Italiana');

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11L09H901L', 'CognomeNono', 'Nono','' ,to_date('1950-01-09','YYYY-MM-DD') , 'Napoli', 'Caserta', 'Via Nono 8', 'Italiana');

Insert into GCA_ANAGRAFICA_PAZIENTI
   (ID_PAZIENTE, CODICE_FISCALE, COGNOME, NOME, SESSO , DATA_NASCITA, LUOGO_NASCITA, LUOGO_RESIDENZA , INDIRIZZO_DOMICILIO , NAZIONALITA)
 Values
   (S_GCA_ANAGRAFICA_PAZIENTI.nextval, 'CDCFSC11M10H901M', 'CognomeDecimo', 'Decimo','' ,to_date('1950-01-10','YYYY-MM-DD') , 'Napoli', 'Palermo', 'Via Decimo 8', 'Italiana');
