SET DEFINE OFF;
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 1, 1);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 1, 22);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 2, 1);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 4, 1);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 4, 3);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (1, 4, 4);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 123);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 124);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 126);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 128);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 148);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 153);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 36, 256);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 37, 21);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 37, 22);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (2, 37, 128);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 41, 21);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 41, 22);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 41, 128);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 41, 164);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 41, 254);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 61, 123);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (58, 61, 128);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 21);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 22);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 123);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 124);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 128);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 131);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 140);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 148);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 153);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 164);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (125, 81, 254);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (135, 85, 21);
Insert into GCA_ESERCIZIO_MEDIA
   (ID_PACCHETTO, ID_ESERCIZIO, ID_MEDIA)
 Values
   (135, 85, 22);
COMMIT;
